# Generated by Django 5.0.2 on 2024-02-22 12:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('item', '0003_rename_categoy_item_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chat',
            new_name='Chats',
        ),
        migrations.RenameField(
            model_name='chatmsg',
            old_name='chat',
            new_name='chats',
        ),
    ]
