# Generated by Django 5.0.2 on 2024-02-22 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_chats_chat_rename_chatmsg_chatmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='chats',
            new_name='chat',
        ),
    ]
